import type { Insight } from "./schema";
import data from "./data.json";

/**
 * Runtime view of the insights corpus.
 *
 * TWO ACCESS PATHS
 *
 *   SYNC (build-time data.json) — for any code path that has to run
 *   in client components or anywhere async isn't acceptable:
 *     - getAllInsights()
 *     - getInsight()
 *     - getLatestInsights()
 *   Reads from /src/lib/insights/data.json, which is generated by
 *   the prebuild script from the MDX files committed in git. This
 *   is the "seed" view: admin edits made on production won't
 *   appear here until the next deploy.
 *
 *   ASYNC (Blob overlay aware) — for server components that want
 *   live admin-edited content:
 *     - getAllInsightsLive()
 *     - getInsightLive()
 *   Reads the SAME seed plus, in production with a Vercel Blob
 *   token, any admin-edited versions that override matching slugs.
 *   Use this in /insights/[slug] and /insights pages with ISR
 *   (revalidate = 60) for a near-realtime read.
 *
 * The homepage Insights section is a Client Component and so uses
 * the sync path — meaning the home's "latest 5" snapshot updates
 * on rebuild, not immediately. The admin's revalidatePath call
 * after a save invalidates the detail + listing pages so those
 * reflect changes within seconds.
 */

const SEED = data as unknown as Insight[];

// ---- SYNC API (data.json view, used by client components) -------

export function getAllInsights(): Insight[] {
  return SEED;
}

export function getInsight(slug: string): Insight | undefined {
  return SEED.find((i) => i.slug === slug);
}

export function getLatestInsights(n: number): Insight[] {
  return SEED.slice(0, n);
}

// ---- ASYNC API (seed + Blob overlay, used by server pages) -------

const BLOB_INSIGHTS_PREFIX = "insights/";

function shouldUseBlob(): boolean {
  return !!process.env.BLOB_READ_WRITE_TOKEN;
}

/**
 * Parse an MDX blob's text into an Insight. Uses gray-matter via
 * a dynamic import so the loader stays tree-shakeable for clients
 * that only need the sync path.
 */
async function parseRaw(filename: string, raw: string): Promise<Insight> {
  const { default: matter } = await import("gray-matter");
  const { data: fm, content } = matter(raw);
  const dateStr =
    fm.date instanceof Date
      ? fm.date.toISOString().slice(0, 10)
      : typeof fm.date === "string"
        ? fm.date
        : "1970-01-01";
  const slug = filename
    .replace(/^\d{4}-\d{2}-\d{2}-/, "")
    .replace(/\.mdx$/, "");
  return {
    title: typeof fm.title === "string" ? fm.title : "",
    date: /^\d{4}-\d{2}-\d{2}$/.test(dateStr) ? dateStr : "1970-01-01",
    category: fm.category,
    excerpt: typeof fm.excerpt === "string" ? fm.excerpt : "",
    readTime: typeof fm.readTime === "string" ? fm.readTime : "",
    image: typeof fm.image === "string" ? fm.image : "/images/about.jpg",
    featured: fm.featured === true,
    video: typeof fm.video === "string" ? fm.video : undefined,
    audio: typeof fm.audio === "string" ? fm.audio : undefined,
    slug,
    body: content.trim(),
    href: `/insights/${slug}`,
  } as Insight;
}

/**
 * Read all Blob-stored overrides. Returns a Map<slug, Insight>
 * so the caller can merge against seed without rescanning.
 *
 * Empty map when Blob isn't configured. Failures are swallowed —
 * if Blob is unreachable, we still want to render seed content.
 */
async function fetchBlobOverrides(): Promise<Map<string, Insight>> {
  if (!shouldUseBlob()) return new Map();
  try {
    const { list } = await import("@vercel/blob");
    const result = await list({ prefix: BLOB_INSIGHTS_PREFIX });
    const entries = await Promise.all(
      result.blobs
        .filter((b) => b.pathname.endsWith(".mdx"))
        .map(async (b) => {
          const filename = b.pathname.replace(BLOB_INSIGHTS_PREFIX, "");
          const raw = await fetch(b.url, { cache: "no-store" }).then((r) =>
            r.text(),
          );
          return parseRaw(filename, raw);
        }),
    );
    return new Map(entries.map((e) => [e.slug, e]));
  } catch (err) {
    console.warn("[insights loader] Blob overlay fetch failed:", err);
    return new Map();
  }
}

/**
 * Live view of every insight — seed merged with Blob overrides,
 * Blob wins on slug collision. Sorted newest-first.
 */
export async function getAllInsightsLive(): Promise<Insight[]> {
  const overrides = await fetchBlobOverrides();
  // Start with seed, override any matching slug from Blob, then
  // add Blob-only entries (new posts created via admin).
  const merged = new Map<string, Insight>();
  for (const seed of SEED) merged.set(seed.slug, seed);
  for (const [slug, override] of overrides) merged.set(slug, override);
  return Array.from(merged.values()).sort((a, b) =>
    b.date.localeCompare(a.date),
  );
}

export async function getInsightLive(
  slug: string,
): Promise<Insight | undefined> {
  const all = await getAllInsightsLive();
  return all.find((i) => i.slug === slug);
}
